### ISSUE TITLE
Error: Cannot find module 'extend'

### ISSUE THREAD

**Issue by prassu99** [sandro-pasquali/products#1]
I have installed  latest npm but I don't know why it is showing error.

**Comment by prassu99** [comment]
Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Prasanna Kumar Marru\Desktop\New folder\products\node_modules\request\index.js:17:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! products@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the products@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the products package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs products
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls products
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Prasanna Kumar Marru\Desktop\New folder\products\products\npm-debug.log

**Comment by sandro-pasquali** [comment]
Hi @prassu99!

This isn't maintained. 

More usefully, can I suggest that you give https://github.com/SBoudrias/Inquirer.js/ a try? I think that's the best lib for what you need.
